float $flomovalue = 1.0;

polySphere;
move 0 $flomovalue 0;

polySphere;
move ($flomovalue *2) $flomovalue 0;

polySphere -r 1.3;
move ($flomovalue *4 + 0.3) ($flomovalue + 0.3) 0;

polyCylinder -r 0.2 -h 1.5;
move ($flomovalue * 4) 3 0.7;
polyCylinder -r 0.2 -h 1.5;
move ($flomovalue * 4) 3 -0.7;

polySphere -r 0.4;
move ($flomovalue * 4) 4 0.7;
polySphere -r 0.4;
move ($flomovalue * 4) 4 -0.7;

polySphere -r 0.4;
move 4.5 1.7 1;
polySphere -r 0.4;
move 4.5 1.7 -1;
